services:

  kms-core:
    container_name: kms-core
    image: ghcr.io/zama-ai/kms-service:v0.11.0-rc5
    env_file:
      - ../env/staging/.env.core.local
    entrypoint:
      - /bin/sh
      - -c
      - |
        set -e
        export AWS_ACCESS_KEY_ID=$$(cat /minio_secrets/access_key)
        export AWS_SECRET_ACCESS_KEY=$$(cat /minio_secrets/secret_key)
        echo '=================GENERATING SIGNING KEYS================='
        kms-gen-keys --pub-url "$$KMS_CORE__PUBLIC_VAULT__STORAGE" --aws-s3-endpoint "$$S3_ENDPOINT" --aws-region "$$S3_REGION" --priv-url "$$KMS_CORE__PRIVATE_VAULT__STORAGE" --cmd signing-keys centralized
        echo '=================STARTING KMS SERVICE================='
        kms-server --config-file config/config.toml
    volumes:
      - httpz_minio_secrets:/minio_secrets
      - ../config/kms-core/config.toml:/app/kms/core/service/config/config.toml
    ports:
      - "50051:50051"
    healthcheck:
      test: "grpc_health_probe --addr=localhost:50051"
      interval: 1s
      timeout: 1s
      retries: 5
      start_period: 1s

  generate-fhe-keys:
    container_name: httpz-generate-fhe-keys
    image: ghcr.io/zama-ai/kms-core-client:v0.11.0-rc5
    env_file:
      - ../env/staging/.env.core.local
    entrypoint:
      - /bin/sh
      - -c
      - |
        set -e
        sleep 10
        cd /app/kms-core-client
        bin/kms-core-client -f config.toml insecure-key-gen
        bin/kms-core-client -f config.toml insecure-crs-gen --max-num-bits 2048

    volumes:
      - httpz_minio_secrets:/minio_secrets
      - ../config/core-client/config.toml:/app/kms-core-client/config.toml
    depends_on:
      kms-core:
        condition: service_started

  update-kms-keys:
    container_name: httpz-update-kms-keys
    image: docker:cli
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ../config/relayer/local.yaml.local:/relayer-local.yaml
      - ../env/staging/.env.coprocessor.local:/env.staging.coprocessor
      - ../env/staging/.env.host.local:/env.staging.host
      - ../env/staging/.env.gateway.local:/env.staging.gateway
      - ../scripts/update-kms-keys.sh:/update-kms-keys.sh
    command: 
      - /bin/sh
      - -c
      - |
        set -e
        apk add --no-cache bash grep sed curl && /bin/bash /update-kms-keys.sh
    depends_on:
      generate-fhe-keys:
        condition: service_completed_successfully

volumes:
  httpz_minio_secrets:
    external: true