services:
  relayer:
    container_name: httpz-relayer
    image: ghcr.io/zama-ai/httpz-relayer:${RELAYER_VERSION}
    env_file:
      - ../env/staging/.env.relayer.local
    command:
    - fhevm-relayer
    volumes: 
      - ../config/relayer/local.yaml.local:/app/config/local.yaml
    ports:
      - "3000:3000"
