services:

  tests-e2e-debug:
    container_name: httpz-tests-e2e-debug
    image: ghcr.io/zama-ai/fhevm-e2e-test:${TESTS_VERSION}
    env_file:
      - ../env/staging/.env.tests.local
    command:
      - /bin/bash
      - -c
      - tail -f /dev/null
