name: "Docker - fhevm E2E Image"

on:
  pull_request:
    paths:
      - .github/workflows/docker-e2e-image.yml
      - e2e_new/**
  push:
    branches:
      - main
    paths:
      - .github/workflows/docker-e2e-image.yml
      - e2e_new/**
  release:
    types:
      - published

concurrency:
  group: e2e-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  docker-e2e-image:
    name: Docker - fhevm E2E Image
    uses: zama-ai/ci-templates/.github/workflows/docker_common.yml@44333c96991d6747e0bef6a3308bfd98b20390f8 # main
    secrets:
      GHCR_ACTION_TOKEN: ${{ secrets.BLOCKCHAIN_ACTIONS_TOKEN }}
      GRAVITON_BUILDER_SSH_PRIVATE_KEY: ${{ secrets.GRAVITON_BUILDER_SSH_PRIVATE_KEY }}
    permissions:
      contents: "read"
      id-token: "write"
      packages: "write"
    with:
      working-directory: "."
      push_image: true
      image-name: "fhevm-test-suite/e2e-new"
      docker-file: "e2e_new/Dockerfile"
      arm-build: true